### ISSUE TITLE
Add a feature

### ISSUE THREAD

**Issue by acyc070** [hypov8/blender_kingpin_models#6]
There is a vertex keys animation type in the import parameters, which only has coordinates. you can make face keys in which things like rotate and scale will appear. and with such things you can do things that are impossible in vertex keys. can you please add this feature?

**Comment by hypov8** [comment]
i am not sure i get what you want. 
a face is 3 vertex. when you scale the face the 3 vertex get moved(in edit mode). 
after edits, you set new key on selected(vertex). it will now "look" like it got scaled

vertex animating is different to object animation.

unless there is something i am missing?

**Comment by acyc070** [comment]
will you try to implement this?

**Comment by hypov8** [comment]
vertex animation is already supported, just use the kingpin toolbar to edit/update keyframes.
its just a cut down version of AnimAll plugin. targeted for kingpin modeling.

if that's not what you refer to, let me know

![image](https://github.com/hypov8/blender_kingpin_models/assets/16630512/160630c6-35e9-4ae8-8992-93f180a09238)
